---

# This is run as user govready

- name: Install python-lxml (used by govready and SSG)
  yum:
    pkg: python-lxml
    state: installed
  ignore_errors: true
  become: yes

- name: Clone SCAP Security Guide (SSG) repository 
  git:
    repo: "{{ ssg_repo }}"
    dest: "{{ ssg_repo_local_destination }}"
    force: yes

- name: Compile SCAP Security Guide content for RHEL 7
  command: chdir="{{ ssg_repo }}" make "{{ ssg_os_version }}"

