---

# Install and compile the SCAP Security Guide (if not already present).

- name: Ensure git and python-lxml (used by govready and SSG) are installed.
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - python-lxml
    - git
  ignore_errors: true

- name: Clone SCAP Security Guide (SSG) repository 
  git:
    repo: "{{ ssg_repo }}"
    dest: "{{ ssg_repo_local_destination }}"

- name: Compile SCAP Security Guide content for RHEL 7
  command: make "{{ ssg_os_version }}"
  args:
    chdir: "{{ ssg_repo_local_destination }}"
    creates: "{{ ssg_creates }}"
